language: objective-c
osx_image: xcode8
script: xcodebuild clean build test -workspace 'RxSwiftUtilities.xcworkspace' -scheme 'RxSwiftUtilities iOS' -destination "platform=iOS Simulator,name=iPhone 6S" -enableCodeCoverage YES
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'RxSwiftUtilities'
